### ISSUE TITLE
Scoreboard update turned on in for placeholders error

### ISSUE THREAD

**Issue by Sreeraj-S** [PetteriM1/SimpleScoreboards#11]
Could not execute taskHandler 1: tried to access field de.theamychan.scoreboard.network.packet.SetScorePacket.type from class io.github.definitlyevil.nukkitdev.ScoreboardUpdateTask
07:52:06 [ERROR] Throwing
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access field de.theamychan.scoreboard.network.packet.SetScorePacket.type from class io.github.definitlyevil.nukkitdev.ScoreboardUpdateTask
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:299) [cloudburst.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [cloudburst.jar:?]
        at cn.nukkit.Server.tick(Server.java:1173) [cloudburst.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:938) [cloudburst.jar:?]
        at cn.nukkit.Server.start(Server.java:906) [cloudburst.jar:?]
        at cn.nukkit.Server.<init>(Server.java:587) [cloudburst.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [cloudburst.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access field de.theamychan.scoreboard.network.packet.SetScorePacket.type from class io.github.definitlyevil.nukkitdev.ScoreboardUpdateTask
        at io.github.definitlyevil.nukkitdev.ScoreboardUpdateTask.process(ScoreboardUpdateTask.java:45) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_275]
        at io.github.definitlyevil.nukkitdev.ScoreboardUpdateTask.run(ScoreboardUpdateTask.java:26) ~[?:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) ~[cloudburst.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) ~[cloudburst.jar:?]
        ... 6 more

this error occurs when a player join the server end when a player leave

**Comment by PetteriM1** [comment]
Delete all scoreboard api plugins and let the plugin to download the correct version

**Comment by Sreeraj-S** [comment]
ok... will that bug the llama economy? 

cause sometimes I am getting placeholder API error in the llama economy. I have created an issue in the llama economy GitHub 
link of that issue:- https://github.com/llamadevelopment/LlamaEconomy/issues/2

Edit:- now it works and the llama economy is working fine
 Thank you for your time helping :)
