### ISSUE TITLE
scoreboard not showing when a person join the server

### ISSUE THREAD

**Issue by Sreeraj-S** [PetteriM1/SimpleScoreboards#13]
FATAL - Could not pass event "cn.nukkit.event.player.PlayerLocallyInitializedEvent" to "SimpleScoreboards v2.4.0": null on me.petterim1.scoreboards.Main
2021-04-24 12:34:39.434 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[cloudburst.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[cloudburst.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:543) [cloudburst.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2246) [cloudburst.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:123) [cloudburst.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:165) [cloudburst.jar:?]
	at cn.nukkit.Server.tick(Server.java:1165) [cloudburst.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:938) [cloudburst.jar:?]
	at cn.nukkit.Server.start(Server.java:906) [cloudburst.jar:?]
	at cn.nukkit.Server.<init>(Server.java:587) [cloudburst.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [cloudburst.jar:?]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at cn.nukkit.utils.ConfigSection.getList(ConfigSection.java:367) ~[cloudburst.jar:?]
	at cn.nukkit.utils.ConfigSection.getList(ConfigSection.java:356) ~[cloudburst.jar:?]
	at cn.nukkit.utils.ConfigSection.getStringList(ConfigSection.java:388) ~[cloudburst.jar:?]
	at cn.nukkit.utils.Config.getStringList(Config.java:356) ~[cloudburst.jar:?]
	at me.petterim1.scoreboards.Main.onJoin(Main.java:64) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[cloudburst.jar:?]
	... 10 more

this error show each time a player join

**Comment by PetteriM1** [comment]
It's a config error. Fix your config.yml file and restart the server.
